/* This file is auto-generated by packages/icons/build/build.mjs */
import type * as React from "react"
export type IconProps = React.SVGProps<SVGSVGElement>;
export declare const CalendarDateIcon: (props: IconProps) => React.JSX.Element;
export declare const ClockIcon: (props: IconProps) => React.JSX.Element;
export declare const DashboardIcon: (props: IconProps) => React.JSX.Element;
export declare const FrameIcon: (props: IconProps) => React.JSX.Element;
export declare const HideIcon: (props: IconProps) => React.JSX.Element;
export declare const HourglassIcon: (props: IconProps) => React.JSX.Element;
export declare const InfoCircleIcon: (props: IconProps) => React.JSX.Element;
export declare const LayoutTopIcon: (props: IconProps) => React.JSX.Element;
export declare const MdiAppleIcon: (props: IconProps) => React.JSX.Element;
export declare const MdiMicrosoftWindowsIcon: (props: IconProps) => React.JSX.Element;
export declare const MinusIcon: (props: IconProps) => React.JSX.Element;
export declare const MoonIcon: (props: IconProps) => React.JSX.Element;
export declare const PlanIcon: (props: IconProps) => React.JSX.Element;
export declare const PlusIcon: (props: IconProps) => React.JSX.Element;
export declare const SettingIcon: (props: IconProps) => React.JSX.Element;
export declare const ShowIcon: (props: IconProps) => React.JSX.Element;
export declare const SunIcon: (props: IconProps) => React.JSX.Element;
export declare const ThumbsUpIcon: (props: IconProps) => React.JSX.Element;
export declare const WidgetIcon: (props: IconProps) => React.JSX.Element;
