/* This file is auto-generated by packages/icons/build/build.mjs */
import type { SVGProps } from "react";
const DefaultIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M19.5 12C19.5 7.85786 16.1421 4.5 12 4.5C7.85786 4.5 4.5 7.85786 4.5 12C4.5 16.1421 7.85786 19.5 12 19.5V21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21V19.5C16.1421 19.5 19.5 16.1421 19.5 12Z" fill="currentColor" /></svg>;
export default DefaultIcon;