/* This file is auto-generated by packages/icons/build/build.mjs */
import type { SVGProps } from "react";
const FrameIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><circle cx={12} cy={12} r={8} stroke="black" strokeWidth={2} /></svg>;
export default FrameIcon;