/* This file is auto-generated by packages/icons/build/build.mjs */
import type { SVGProps } from "react";
const MdiMicrosoftWindowsIcon = (props: SVGProps<SVGSVGElement>) => <svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><path d="M3 12V6.75L9 5.43V11.91L3 12ZM20 3V11.75L10 11.9V5.21L20 3ZM3 13L9 13.09V19.9L3 18.75V13ZM20 13.25V22L10 20.09V13.1L20 13.25Z" fill="black" /></svg>;
export default MdiMicrosoftWindowsIcon;