/* This file is auto-generated by packages/icons/build/build.mjs */
import type { SVGProps } from "react";
const MinusIcon = (props: SVGProps<SVGSVGElement>) => <svg preserveAspectRatio="none" width="1em" height="1em" overflow="visible" style={{
  display: "block"
}} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}><g id="minus"><path id="Icon" d="M5 12H19" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" /></g></svg>;
export default MinusIcon;